category_key: television
confidence: 0.16666666666666666
field_mappings:
  release_date: Release Date
file_pattern: television.xlsx
fingerprint: fecdd41bc8b3cc93a734f4527d1203d34e17325648de452eaa0cc783cceaa6b8
format_name: xlsx
header_row_index: 1
normalizer_options: {}
profile_name: television
sheet_name: Streaming Jun-Jul 2026
source_role: event_source
