"""Core package exports."""

from .config import load_settings
from .csv_export import (
    DEFAULT_OUTPUT_DIR,
    build_generated_csv_path,
    sanitize_filename_component,
    write_generated_csv,
    write_generated_csv_auto,
)
from .date_rules import QuestionDates, compute_question_dates
from .dedup import (
    DEFAULT_SIMILARITY_THRESHOLD,
    DeduplicationResult,
    NearDuplicatePair,
    deduplicate,
    row_hash,
    write_flagged_csv,
)
from .generation import (
    BatchExecutor,
    BatchResult,
    build_cost_summary,
    build_event_string,
    estimate_cost,
    extract_token_usage,
    FailedBatch,
    GeneratedQuestion,
    GeneratedQuestionBatch,
    log_cost_summary,
    OUTPUT_COLUMNS,
    OutputRow,
    PromptBuilder,
    PromptConfig,
    PromptItem,
    RowAssembler,
    RunCostSummary,
    TokenUsage,
)
from .parsers import load_normalized_bundle
from .pipeline import PipelineResult, run_pipeline
from .qa_summary import (
    QASummary,
    build_qa_summary,
    format_qa_summary,
    print_qa_summary,
)
from .schema_validator import (
    DATE_FIELDS,
    REQUIRED_FIELDS,
    RowValidationError,
    VALID_ANSWER_TYPES,
    validate_row,
    validate_rows,
    ValidationResult,
    write_errors_csv,
)

__all__ = [
    "BatchExecutor",
    "BatchResult",
    "build_cost_summary",
    "build_event_string",
    "compute_question_dates",
    "DEFAULT_OUTPUT_DIR",
    "build_generated_csv_path",
    "deduplicate",
    "DeduplicationResult",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "estimate_cost",
    "extract_token_usage",
    "FailedBatch",
    "GeneratedQuestion",
    "GeneratedQuestionBatch",
    "load_normalized_bundle",
    "load_settings",
    "PipelineResult",
    "log_cost_summary",
    "NearDuplicatePair",
    "OUTPUT_COLUMNS",
    "OutputRow",
    "PromptBuilder",
    "print_qa_summary",
    "run_pipeline",
    "PromptConfig",
    "PromptItem",
    "QASummary",
    "QuestionDates",
    "REQUIRED_FIELDS",
    "row_hash",
    "sanitize_filename_component",
    "RowAssembler",
    "RowValidationError",
    "RunCostSummary",
    "TokenUsage",
    "VALID_ANSWER_TYPES",
    "build_qa_summary",
    "format_qa_summary",
    "validate_row",
    "validate_rows",
    "ValidationResult",
    "write_errors_csv",
    "write_flagged_csv",
    "write_generated_csv",
    "write_generated_csv_auto",
]
