#!/usr/bin/env python3
"""Generate config/team_aliases/*.yaml from embedded roster definitions."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "config" / "team_aliases"


def _team(code: str, *aliases: str) -> dict:
    names = [code, *aliases]
    return {"code": code, "aliases": list(dict.fromkeys(names))}


def _write(
    name: str,
    package_key: str,
    teams: list[dict],
    *,
    package_aliases: list[str] | None = None,
) -> None:
    payload: dict = {"package_key": package_key, "teams": teams}
    if package_aliases:
        payload["package_aliases"] = package_aliases
    path = OUT / f"{name}.yaml"
    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(payload, handle, sort_keys=False, allow_unicode=True, default_flow_style=False)


def _from_rows(rows: list[tuple]) -> list[dict]:
    return [_team(code, *rest) for code, *rest in rows]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    _write("mlb", "mlb", _from_rows([
        ("ARI", "Arizona Diamondbacks", "Diamondbacks", "D-backs"),
        ("ATL", "Atlanta Braves", "Braves"),
        ("ATH", "Athletics"),
        ("BAL", "Baltimore Orioles", "Orioles"),
        ("BOS", "Boston Red Sox", "Red Sox"),
        ("CHC", "Chicago Cubs", "Cubs"),
        ("CHW", "Chicago White Sox", "White Sox"),
        ("CIN", "Cincinnati Reds", "Reds"),
        ("CLE", "Cleveland Guardians", "Guardians"),
        ("COL", "Colorado Rockies", "Rockies"),
        ("DET", "Detroit Tigers", "Tigers"),
        ("HOU", "Houston Astros", "Astros"),
        ("KCR", "Kansas City Royals", "Royals"),
        ("LAA", "Los Angeles Angels", "Angels"),
        ("LAD", "Los Angeles Dodgers", "Dodgers"),
        ("MIA", "Miami Marlins", "Marlins"),
        ("MIL", "Milwaukee Brewers", "Brewers"),
        ("MIN", "Minnesota Twins", "Twins"),
        ("NYM", "New York Mets", "Mets"),
        ("NYY", "New York Yankees", "Yankees"),
        ("PHI", "Philadelphia Phillies", "Phillies"),
        ("PIT", "Pittsburgh Pirates", "Pirates"),
        ("SDP", "San Diego Padres", "Padres"),
        ("SFG", "San Francisco Giants", "Giants"),
        ("SEA", "Seattle Mariners", "Mariners"),
        ("STL", "St. Louis Cardinals", "Cardinals"),
        ("TBR", "Tampa Bay Rays", "Rays"),
        ("TEX", "Texas Rangers", "Rangers"),
        ("TOR", "Toronto Blue Jays", "Blue Jays"),
        ("WSN", "Washington Nationals", "Nationals"),
    ]))

    _write("wnba", "wnba", _from_rows([
        ("ATL", "Atlanta Dream", "Dream"),
        ("CHI", "Chicago Sky", "Sky"),
        ("CON", "Connecticut Sun", "Sun"),
        ("DAL", "Dallas Wings", "Wings"),
        ("GS", "Golden State Valkyries", "Valkyries"),
        ("IND", "Indiana Fever", "Fever"),
        ("LV", "Las Vegas Aces", "Aces"),
        ("LA", "Los Angeles Sparks", "Sparks"),
        ("MIN", "Minnesota Lynx", "Lynx"),
        ("NY", "New York Liberty", "Liberty"),
        ("PHX", "Phoenix Mercury", "Mercury"),
        ("POR", "Portland Fire", "Fire"),
        ("SEA", "Seattle Storm", "Storm"),
        ("TOR", "Toronto Tempo", "Tempo"),
        ("WSH", "Washington Mystics", "Mystics"),
    ]), package_aliases=["WNBA"])

    _write("mls", "mls", _from_rows([
        ("ATL", "Atlanta United", "Atlanta United FC"),
        ("ATX", "Austin FC"),
        ("CLT", "Charlotte FC"),
        ("CHI", "Chicago Fire", "Chicago Fire FC"),
        ("CIN", "FC Cincinnati", "Cincinnati"),
        ("COL", "Colorado Rapids"),
        ("CLB", "Columbus Crew"),
        ("DCU", "D.C. United", "DC United"),
        ("DAL", "FC Dallas"),
        ("HOU", "Houston Dynamo", "Houston Dynamo FC"),
        ("MIA", "Inter Miami CF", "Inter Miami"),
        ("LAFC", "Los Angeles FC"),
        ("LAG", "LA Galaxy", "Los Angeles Galaxy", "Galaxy"),
        ("MIN", "Minnesota United", "Minnesota United FC"),
        ("MTL", "CF Montréal", "CF Montreal", "Montreal"),
        ("NSH", "Nashville SC"),
        ("NE", "New England Revolution", "Revolution"),
        ("NYC", "New York City FC", "NYCFC"),
        ("NYRB", "New York Red Bulls", "Red Bulls"),
        ("ORL", "Orlando City", "Orlando City SC"),
        ("PHI", "Philadelphia Union"),
        ("POR", "Portland Timbers", "Timbers"),
        ("RSL", "Real Salt Lake"),
        ("SD", "San Diego FC"),
        ("SJ", "San Jose Earthquakes", "Earthquakes"),
        ("SEA", "Seattle Sounders", "Seattle Sounders FC"),
        ("SKC", "Sporting Kansas City", "Sporting KC"),
        ("STL", "St. Louis CITY SC", "St. Louis City SC"),
        ("TOR", "Toronto FC"),
        ("VAN", "Vancouver Whitecaps", "Vancouver Whitecaps FC"),
    ]), package_aliases=["MLS", "Major League Soccer"])

    _write("nwsl", "nwsl", _from_rows([
        ("KC", "Kansas City Current", "Current"),
        ("CHI", "Chicago Stars FC", "Chicago Red Stars"),
        ("DAL", "Dallas Trinity FC"),
        ("HOU", "Houston Dash", "Dash"),
        ("GS", "Bay FC"),
        ("LOU", "Racing Louisville FC", "Louisville"),
        ("LA", "Angel City FC", "Angel City"),
        ("MIN", "Minnesota Aurora FC"),
        ("NJ", "NJ/NY Gotham FC", "Gotham FC", "Gotham"),
        ("NC", "North Carolina Courage", "Courage"),
        ("ORL", "Orlando Pride", "Pride"),
        ("POR", "Portland Thorns FC", "Portland Thorns", "Thorns"),
        ("SEA", "Seattle Reign FC", "Reign FC", "Reign"),
        ("SD", "San Diego Wave FC", "Wave FC", "Wave"),
        ("WAS", "Washington Spirit", "Spirit"),
    ]), package_aliases=["NWSL"])

    _write("laliga", "laliga", _from_rows([
        ("RMA", "Real Madrid"),
        ("BAR", "Barcelona", "FC Barcelona"),
        ("ATM", "Atlético Madrid", "Atletico Madrid", "Atletico"),
        ("GIR", "Girona", "Girona FC"),
        ("ATH", "Athletic Club", "Athletic Bilbao", "Athletic"),
        ("RSO", "Real Sociedad", "Sociedad"),
        ("BET", "Real Betis", "Betis"),
        ("VLL", "Real Valladolid", "Valladolid"),
        ("OSA", "Osasuna", "CA Osasuna"),
        ("CEL", "Celta Vigo", "Celta"),
        ("SEV", "Sevilla", "Sevilla FC"),
        ("VAL", "Valencia", "Valencia CF"),
        ("GET", "Getafe", "Getafe CF"),
        ("ALA", "Alavés", "Alaves", "Deportivo Alavés"),
        ("LEG", "Leganés", "Leganes"),
        ("LAS", "UD Las Palmas", "Las Palmas"),
        ("MLL", "Mallorca", "RCD Mallorca"),
        ("RAY", "Rayo Vallecano", "Rayo"),
        ("CAD", "Cádiz", "Cadiz", "Cádiz CF"),
        ("GRA", "Granada", "Granada CF"),
        ("ESP", "Espanyol", "RCD Espanyol"),
        ("VIL", "Villarreal", "Villarreal CF"),
    ]), package_aliases=["La Liga", "LaLiga"])

    _write("nba", "nba", _from_rows([
        ("ATL", "Atlanta Hawks", "Hawks"),
        ("BOS", "Boston Celtics", "Celtics"),
        ("BKN", "Brooklyn Nets", "Nets"),
        ("CHA", "Charlotte Hornets", "Hornets"),
        ("CHI", "Chicago Bulls", "Bulls"),
        ("CLE", "Cleveland Cavaliers", "Cavaliers", "Cavs"),
        ("DAL", "Dallas Mavericks", "Mavericks", "Mavs"),
        ("DEN", "Denver Nuggets", "Nuggets"),
        ("DET", "Detroit Pistons", "Pistons"),
        ("GSW", "Golden State Warriors", "Warriors"),
        ("HOU", "Houston Rockets", "Rockets"),
        ("IND", "Indiana Pacers", "Pacers"),
        ("LAC", "Los Angeles Clippers", "Clippers", "LA Clippers"),
        ("LAL", "Los Angeles Lakers", "Lakers", "LA Lakers"),
        ("MEM", "Memphis Grizzlies", "Grizzlies"),
        ("MIA", "Miami Heat", "Heat"),
        ("MIL", "Milwaukee Bucks", "Bucks"),
        ("MIN", "Minnesota Timberwolves", "Timberwolves", "Wolves"),
        ("NOP", "New Orleans Pelicans", "Pelicans"),
        ("NYK", "New York Knicks", "Knicks"),
        ("OKC", "Oklahoma City Thunder", "Thunder"),
        ("ORL", "Orlando Magic", "Magic"),
        ("PHI", "Philadelphia 76ers", "76ers", "Sixers"),
        ("PHX", "Phoenix Suns", "Suns"),
        ("POR", "Portland Trail Blazers", "Trail Blazers", "Blazers"),
        ("SAC", "Sacramento Kings", "Kings"),
        ("SAS", "San Antonio Spurs", "Spurs"),
        ("TOR", "Toronto Raptors", "Raptors"),
        ("UTA", "Utah Jazz", "Jazz"),
        ("WAS", "Washington Wizards", "Wizards"),
    ]), package_aliases=["NBA"])

    _write("nfl", "nfl", _from_rows([
        ("ARI", "Arizona Cardinals", "Cardinals"),
        ("ATL", "Atlanta Falcons", "Falcons"),
        ("BAL", "Baltimore Ravens", "Ravens"),
        ("BUF", "Buffalo Bills", "Bills"),
        ("CAR", "Carolina Panthers", "Panthers"),
        ("CHI", "Chicago Bears", "Bears"),
        ("CIN", "Cincinnati Bengals", "Bengals"),
        ("CLE", "Cleveland Browns", "Browns"),
        ("DAL", "Dallas Cowboys", "Cowboys"),
        ("DEN", "Denver Broncos", "Broncos"),
        ("DET", "Detroit Lions", "Lions"),
        ("GB", "Green Bay Packers", "Packers"),
        ("HOU", "Houston Texans", "Texans"),
        ("IND", "Indianapolis Colts", "Colts"),
        ("JAX", "Jacksonville Jaguars", "Jaguars"),
        ("KC", "Kansas City Chiefs", "Chiefs"),
        ("LAC", "Los Angeles Chargers", "Chargers", "LA Chargers"),
        ("LAR", "Los Angeles Rams", "Rams", "LA Rams"),
        ("LV", "Las Vegas Raiders", "Raiders"),
        ("MIA", "Miami Dolphins", "Dolphins"),
        ("MIN", "Minnesota Vikings", "Vikings"),
        ("NE", "New England Patriots", "Patriots"),
        ("NO", "New Orleans Saints", "Saints"),
        ("NYG", "New York Giants", "Giants"),
        ("NYJ", "New York Jets", "Jets"),
        ("PHI", "Philadelphia Eagles", "Eagles"),
        ("PIT", "Pittsburgh Steelers", "Steelers"),
        ("SEA", "Seattle Seahawks", "Seahawks"),
        ("SF", "San Francisco 49ers", "49ers"),
        ("TB", "Tampa Bay Buccaneers", "Buccaneers"),
        ("TEN", "Tennessee Titans", "Titans"),
        ("WAS", "Washington Commanders", "Commanders"),
    ]), package_aliases=["NFL"])

    _write("nhl", "nhl", _from_rows([
        ("ANA", "Anaheim Ducks", "Ducks"),
        ("BOS", "Boston Bruins", "Bruins"),
        ("BUF", "Buffalo Sabres", "Sabres"),
        ("CGY", "Calgary Flames", "Flames"),
        ("CAR", "Carolina Hurricanes", "Hurricanes"),
        ("CHI", "Chicago Blackhawks", "Blackhawks"),
        ("COL", "Colorado Avalanche", "Avalanche"),
        ("CBJ", "Columbus Blue Jackets", "Blue Jackets"),
        ("DAL", "Dallas Stars", "Stars"),
        ("DET", "Detroit Red Wings", "Red Wings"),
        ("EDM", "Edmonton Oilers", "Oilers"),
        ("FLA", "Florida Panthers", "Panthers"),
        ("LAK", "Los Angeles Kings", "Kings", "LA Kings"),
        ("MIN", "Minnesota Wild", "Wild"),
        ("MTL", "Montreal Canadiens", "Canadiens"),
        ("NSH", "Nashville Predators", "Predators"),
        ("NJD", "New Jersey Devils", "Devils"),
        ("NYI", "New York Islanders", "Islanders"),
        ("NYR", "New York Rangers", "Rangers"),
        ("OTT", "Ottawa Senators", "Senators"),
        ("PHI", "Philadelphia Flyers", "Flyers"),
        ("PIT", "Pittsburgh Penguins", "Penguins"),
        ("SJS", "San Jose Sharks", "Sharks"),
        ("SEA", "Seattle Kraken", "Kraken"),
        ("STL", "St. Louis Blues", "Blues"),
        ("TBL", "Tampa Bay Lightning", "Lightning"),
        ("TOR", "Toronto Maple Leafs", "Maple Leafs"),
        ("UTA", "Utah Hockey Club", "Utah HC"),
        ("VAN", "Vancouver Canucks", "Canucks"),
        ("VGK", "Vegas Golden Knights", "Golden Knights"),
        ("WPG", "Winnipeg Jets", "Jets"),
        ("WSH", "Washington Capitals", "Capitals"),
    ]), package_aliases=["NHL"])

    _write_college(
        "ncaaf",
        "ncaaf",
        _school_names_only(NCAAF_FBS),
        disambig=NCAAF_DISAMBIG,
        package_aliases=["NCAA Football", "college football"],
    )
    _write_college(
        "ncaab",
        "ncaab",
        _school_names_only(NCAAB_D1),
        disambig=NCAAB_DISAMBIG,
        package_aliases=["NCAA Basketball", "college basketball"],
    )

    print(f"Wrote team alias YAML files to {OUT}")


# Extra aliases that are unique across the file (disambiguation / common abbrevs).
NCAAF_DISAMBIG: list[tuple[str, ...]] = [
    ("Miami", "Miami (FL)"),
    ("Miami (Ohio)", "Miami OH"),
    ("USC", "Southern California"),
    ("LSU", "Louisiana State"),
    ("NC State", "North Carolina State"),
    ("Ole Miss", "Mississippi"),
    ("UCF", "Central Florida"),
    ("California", "Cal"),
    ("Pittsburgh", "Pitt"),
    ("Louisiana-Monroe", "ULM"),
    ("Louisiana", "UL Lafayette"),
    ("Connecticut", "UConn"),
    ("Southern Miss", "Southern Mississippi"),
    ("Hawaii", "Hawai'i"),
    ("Florida International", "FIU"),
    ("Florida Atlantic", "FAU"),
    ("South Florida", "USF"),
    ("West Virginia", "WVU"),
    ("Virginia Tech", "VT"),
]

NCAAB_DISAMBIG: list[tuple[str, ...]] = [
    ("Miami", "Miami (FL)"),
    ("Miami (Ohio)", "Miami OH"),
    ("USC", "Southern California"),
    ("LSU", "Louisiana State"),
    ("NC State", "North Carolina State"),
    ("Ole Miss", "Mississippi"),
    ("UCF", "Central Florida"),
    ("California", "Cal"),
    ("Pittsburgh", "Pitt"),
    ("Connecticut", "UConn"),
    ("Massachusetts", "UMass"),
    ("Southern Miss", "Southern Mississippi"),
    ("Virginia Commonwealth", "VCU"),
    ("Saint Joseph's", "Saint Josephs"),
    ("St. John's", "St. Johns"),
    ("William & Mary", "William and Mary"),
    ("Pennsylvania", "Penn"),
    ("Illinois-Chicago", "UIC"),
    ("SIU Edwardsville", "SIUE"),
    ("NC A&T", "North Carolina A&T"),
    ("NC Central", "North Carolina Central"),
    ("Florida International", "FIU"),
    ("Florida Atlantic", "FAU"),
    ("South Florida", "USF"),
]

# FBS schools — canonical = full school name (mascot nicknames omitted; see DISAMBIG).
NCAAF_FBS: list[tuple[str, ...]] = [
    ("Air Force", "Falcons"),
    ("Akron", "Zips"),
    ("Alabama", "Crimson Tide"),
    ("Appalachian State", "App State", "Mountaineers"),
    ("Arizona", "Wildcats"),
    ("Arizona State", "Sun Devils"),
    ("Arkansas", "Razorbacks"),
    ("Arkansas State", "Red Wolves"),
    ("Army", "Black Knights"),
    ("Auburn", "Tigers"),
    ("Ball State", "Cardinals"),
    ("Baylor", "Bears"),
    ("Boise State", "Broncos"),
    ("Boston College", "Eagles"),
    ("Bowling Green", "Falcons"),
    ("Buffalo", "Bulls"),
    ("BYU", "Cougars"),
    ("California", "Cal", "Golden Bears"),
    ("Central Michigan", "Chippewas"),
    ("Charlotte", "49ers"),
    ("Cincinnati", "Bearcats"),
    ("Clemson", "Tigers"),
    ("Coastal Carolina", "Chanticleers"),
    ("Colorado", "Buffaloes"),
    ("Colorado State", "Rams"),
    ("Connecticut", "UConn", "Huskies"),
    ("Duke", "Blue Devils"),
    ("East Carolina", "Pirates"),
    ("Eastern Michigan", "Eagles"),
    ("Florida", "Gators"),
    ("Florida Atlantic", "FAU", "Owls"),
    ("Florida International", "FIU", "Panthers"),
    ("Florida State", "Seminoles"),
    ("Fresno State", "Bulldogs"),
    ("Georgia", "Bulldogs"),
    ("Georgia Southern", "Eagles"),
    ("Georgia State", "Panthers"),
    ("Georgia Tech", "Yellow Jackets"),
    ("Hawaii", "Rainbow Warriors"),
    ("Houston", "Cougars"),
    ("Illinois", "Fighting Illini"),
    ("Indiana", "Hoosiers"),
    ("Iowa", "Hawkeyes"),
    ("Iowa State", "Cyclones"),
    ("Jacksonville State", "Gamecocks"),
    ("James Madison", "Dukes"),
    ("Kansas", "Jayhawks"),
    ("Kansas State", "Wildcats"),
    ("Kennesaw State", "Owls"),
    ("Kent State", "Golden Flashes"),
    ("Kentucky", "Wildcats"),
    ("Liberty", "Flames"),
    ("Louisiana", "Ragin' Cajuns", "UL Lafayette"),
    ("Louisiana Tech", "Bulldogs"),
    ("Louisiana-Monroe", "ULM", "Warhawks"),
    ("Louisville", "Cardinals"),
    ("LSU", "Tigers"),
    ("Marshall", "Thundering Herd"),
    ("Maryland", "Terrapins"),
    ("Memphis", "Tigers"),
    ("Miami", "Miami (FL)", "Hurricanes"),
    ("Miami (Ohio)", "Miami OH", "RedHawks"),
    ("Michigan", "Wolverines"),
    ("Michigan State", "Spartans"),
    ("Middle Tennessee", "Blue Raiders"),
    ("Minnesota", "Golden Gophers"),
    ("Mississippi State", "Bulldogs"),
    ("Missouri", "Tigers"),
    ("Navy", "Midshipmen"),
    ("NC State", "North Carolina State", "Wolfpack"),
    ("Nebraska", "Cornhuskers"),
    ("Nevada", "Wolf Pack"),
    ("New Mexico", "Lobos"),
    ("New Mexico State", "Aggies"),
    ("North Carolina", "Tar Heels"),
    ("North Texas", "Mean Green"),
    ("Northern Illinois", "Huskies"),
    ("Northwestern", "Wildcats"),
    ("Notre Dame", "Fighting Irish"),
    ("Ohio", "Bobcats"),
    ("Ohio State", "Buckeyes"),
    ("Oklahoma", "Sooners"),
    ("Oklahoma State", "Cowboys"),
    ("Old Dominion", "Monarchs"),
    ("Ole Miss", "Mississippi", "Rebels"),
    ("Oregon", "Ducks"),
    ("Oregon State", "Beavers"),
    ("Penn State", "Nittany Lions"),
    ("Pittsburgh", "Pitt", "Panthers"),
    ("Purdue", "Boilermakers"),
    ("Rice", "Owls"),
    ("Rutgers", "Scarlet Knights"),
    ("Sam Houston", "Bearkats"),
    ("San Diego State", "Aztecs"),
    ("San Jose State", "Spartans"),
    ("SMU", "Mustangs"),
    ("South Alabama", "Jaguars"),
    ("South Carolina", "Gamecocks"),
    ("South Florida", "USF", "Bulls"),
    ("Southern Miss", "Golden Eagles"),
    ("Stanford", "Cardinal"),
    ("Syracuse", "Orange"),
    ("TCU", "Horned Frogs"),
    ("Temple", "Owls"),
    ("Tennessee", "Volunteers", "Vols"),
    ("Texas", "Longhorns"),
    ("Texas A&M", "Aggies"),
    ("Texas State", "Bobcats"),
    ("Texas Tech", "Red Raiders"),
    ("Toledo", "Rockets"),
    ("Troy", "Trojans"),
    ("Tulane", "Green Wave"),
    ("Tulsa", "Golden Hurricane"),
    ("UAB", "Blazers"),
    ("UCF", "Knights"),
    ("UCLA", "Bruins"),
    ("UNLV", "Rebels"),
    ("USC", "Trojans"),
    ("Utah", "Utes"),
    ("Utah State", "Aggies"),
    ("UTEP", "Miners"),
    ("UTSA", "Roadrunners"),
    ("Vanderbilt", "Commodores"),
    ("Virginia", "Cavaliers"),
    ("Virginia Tech", "Hokies"),
    ("Wake Forest", "Demon Deacons"),
    ("Washington", "Huskies"),
    ("Washington State", "Cougars"),
    ("West Virginia", "Mountaineers"),
    ("Western Kentucky", "Hilltoppers"),
    ("Western Michigan", "Broncos"),
    ("Wisconsin", "Badgers"),
    ("Wyoming", "Cowboys"),
]


# D-I men's basketball — canonical = full school name
NCAAB_D1: list[tuple[str, ...]] = [
    ("Abilene Christian", "Wildcats"),
    ("Air Force", "Falcons"),
    ("Akron", "Zips"),
    ("Alabama", "Crimson Tide"),
    ("Alabama A&M", "Bulldogs"),
    ("Alabama State", "Hornets"),
    ("Albany", "Great Danes"),
    ("Alcorn State", "Braves"),
    ("American", "Eagles"),
    ("Appalachian State", "Mountaineers"),
    ("Arizona", "Wildcats"),
    ("Arizona State", "Sun Devils"),
    ("Arkansas", "Razorbacks"),
    ("Arkansas State", "Red Wolves"),
    ("Arkansas-Pine Bluff", "Golden Lions"),
    ("Army", "Black Knights"),
    ("Auburn", "Tigers"),
    ("Austin Peay", "Governors"),
    ("Ball State", "Cardinals"),
    ("Baylor", "Bears"),
    ("Bellarmine", "Knights"),
    ("Belmont", "Bruins"),
    ("Bethune-Cookman", "Wildcats"),
    ("Binghamton", "Bearcats"),
    ("Boise State", "Broncos"),
    ("Boston College", "Eagles"),
    ("Boston University", "Terriers"),
    ("Bowling Green", "Falcons"),
    ("Bradley", "Braves"),
    ("Brown", "Bears"),
    ("Bryant", "Bulldogs"),
    ("Bucknell", "Bison"),
    ("Buffalo", "Bulls"),
    ("Butler", "Bulldogs"),
    ("BYU", "Cougars"),
    ("Cal Baptist", "California Baptist", "Lancers"),
    ("Cal Poly", "Mustangs"),
    ("Cal State Bakersfield", "Roadrunners"),
    ("Cal State Fullerton", "Titans"),
    ("Cal State Northridge", "Matadors"),
    ("California", "Cal", "Golden Bears"),
    ("Campbell", "Fighting Camels"),
    ("Canisius", "Golden Griffins"),
    ("Central Arkansas", "Bears"),
    ("Central Connecticut", "Blue Devils"),
    ("Central Michigan", "Chippewas"),
    ("Charleston", "Cougars"),
    ("Charleston Southern", "Buccaneers"),
    ("Charlotte", "49ers"),
    ("Chattanooga", "Mocs"),
    ("Chicago State", "Cougars"),
    ("Cincinnati", "Bearcats"),
    ("Clemson", "Tigers"),
    ("Cleveland State", "Vikings"),
    ("Coastal Carolina", "Chanticleers"),
    ("Colgate", "Raiders"),
    ("Colorado", "Buffaloes"),
    ("Colorado State", "Rams"),
    ("Columbia", "Lions"),
    ("Connecticut", "UConn", "Huskies"),
    ("Coppin State", "Eagles"),
    ("Cornell", "Big Red"),
    ("Creighton", "Bluejays"),
    ("Dartmouth", "Big Green"),
    ("Davidson", "Wildcats"),
    ("Dayton", "Flyers"),
    ("Delaware", "Blue Hens"),
    ("Delaware State", "Hornets"),
    ("Denver", "Pioneers"),
    ("DePaul", "Blue Demons"),
    ("Detroit Mercy", "Titans"),
    ("Drake", "Bulldogs"),
    ("Drexel", "Dragons"),
    ("Duke", "Blue Devils"),
    ("Duquesne", "Dukes"),
    ("East Carolina", "Pirates"),
    ("East Tennessee State", "Buccaneers"),
    ("Eastern Illinois", "Panthers"),
    ("Eastern Kentucky", "Colonels"),
    ("Eastern Michigan", "Eagles"),
    ("Eastern Washington", "Eagles"),
    ("Elon", "Phoenix"),
    ("Evansville", "Purple Aces"),
    ("Fairfield", "Stags"),
    ("Fairleigh Dickinson", "Knights"),
    ("Florida", "Gators"),
    ("Florida A&M", "Rattlers"),
    ("Florida Atlantic", "FAU", "Owls"),
    ("Florida Gulf Coast", "Eagles"),
    ("Florida International", "FIU", "Panthers"),
    ("Florida State", "Seminoles"),
    ("Fordham", "Rams"),
    ("Fresno State", "Bulldogs"),
    ("Furman", "Paladins"),
    ("Gardner-Webb", "Runnin' Bulldogs"),
    ("George Mason", "Patriots"),
    ("George Washington", "Revolutionaries"),
    ("Georgetown", "Hoyas"),
    ("Georgia", "Bulldogs"),
    ("Georgia Southern", "Eagles"),
    ("Georgia State", "Panthers"),
    ("Georgia Tech", "Yellow Jackets"),
    ("Gonzaga", "Bulldogs"),
    ("Grambling State", "Tigers"),
    ("Grand Canyon", "Antelopes"),
    ("Green Bay", "Phoenix"),
    ("Hampton", "Pirates"),
    ("Harvard", "Crimson"),
    ("Hawaii", "Rainbow Warriors"),
    ("High Point", "Panthers"),
    ("Hofstra", "Pride"),
    ("Holy Cross", "Crusaders"),
    ("Houston", "Cougars"),
    ("Houston Christian", "Huskies"),
    ("Howard", "Bison"),
    ("Idaho", "Vandals"),
    ("Idaho State", "Bengals"),
    ("Illinois", "Fighting Illini"),
    ("Illinois State", "Redbirds"),
    ("Illinois-Chicago", "UIC", "Flames"),
    ("Incarnate Word", "Cardinals"),
    ("Indiana", "Hoosiers"),
    ("Indiana State", "Sycamores"),
    ("Iona", "Gaels"),
    ("Iowa", "Hawkeyes"),
    ("Iowa State", "Cyclones"),
    ("Jackson State", "Tigers"),
    ("Jacksonville", "Dolphins"),
    ("Jacksonville State", "Gamecocks"),
    ("James Madison", "Dukes"),
    ("Kansas", "Jayhawks"),
    ("Kansas City", "Roos"),
    ("Kansas State", "Wildcats"),
    ("Kennesaw State", "Owls"),
    ("Kent State", "Golden Flashes"),
    ("Kentucky", "Wildcats"),
    ("La Salle", "Explorers"),
    ("Lafayette", "Leopards"),
    ("Lamar", "Cardinals"),
    ("Lehigh", "Mountain Hawks"),
    ("Liberty", "Flames"),
    ("Lindenwood", "Lions"),
    ("Lipscomb", "Bisons"),
    ("Little Rock", "Trojans"),
    ("Long Beach State", "Beach"),
    ("Longwood", "Lancers"),
    ("Louisiana", "Ragin' Cajuns"),
    ("Louisiana Tech", "Bulldogs"),
    ("Louisiana-Monroe", "Warhawks"),
    ("Louisville", "Cardinals"),
    ("Loyola Chicago", "Ramblers"),
    ("Loyola Maryland", "Greyhounds"),
    ("Loyola Marymount", "Lions"),
    ("LSU", "Tigers"),
    ("Maine", "Black Bears"),
    ("Manhattan", "Jaspers"),
    ("Marist", "Red Foxes"),
    ("Marquette", "Golden Eagles"),
    ("Marshall", "Thundering Herd"),
    ("Maryland", "Terrapins"),
    ("Maryland-Eastern Shore", "Hawks"),
    ("Massachusetts", "UMass", "Minutemen"),
    ("McNeese", "Cowboys"),
    ("Memphis", "Tigers"),
    ("Mercer", "Bears"),
    ("Merrimack", "Warriors"),
    ("Miami", "Miami (FL)", "Hurricanes"),
    ("Miami (Ohio)", "Miami OH", "RedHawks"),
    ("Michigan", "Wolverines"),
    ("Michigan State", "Spartans"),
    ("Middle Tennessee", "Blue Raiders"),
    ("Milwaukee", "Panthers"),
    ("Minnesota", "Golden Gophers"),
    ("Mississippi State", "Bulldogs"),
    ("Mississippi Valley State", "Delta Devils"),
    ("Missouri", "Tigers"),
    ("Missouri State", "Bears"),
    ("Monmouth", "Hawks"),
    ("Montana", "Grizzlies"),
    ("Montana State", "Bobcats"),
    ("Morehead State", "Eagles"),
    ("Morgan State", "Bears"),
    ("Mount St. Mary's", "Mount Saint Mary's", "Mount St. Marys"),
    ("Murray State", "Racers"),
    ("Navy", "Midshipmen"),
    ("NC A&T", "North Carolina A&T", "Aggies"),
    ("NC Central", "North Carolina Central", "Eagles"),
    ("NC State", "North Carolina State", "Wolfpack"),
    ("Nebraska", "Cornhuskers"),
    ("Nevada", "Wolf Pack"),
    ("New Hampshire", "Wildcats"),
    ("New Mexico", "Lobos"),
    ("New Mexico State", "Aggies"),
    ("New Orleans", "Privateers"),
    ("Niagara", "Purple Eagles"),
    ("Nicholls", "Colonels"),
    ("Norfolk State", "Spartans"),
    ("North Alabama", "Lions"),
    ("North Carolina", "Tar Heels"),
    ("North Dakota", "Fighting Hawks"),
    ("North Dakota State", "Bison"),
    ("North Florida", "Ospreys"),
    ("North Texas", "Mean Green"),
    ("Northeastern", "Huskies"),
    ("Northern Arizona", "Lumberjacks"),
    ("Northern Colorado", "Bears"),
    ("Northern Illinois", "Huskies"),
    ("Northern Iowa", "Panthers"),
    ("Northern Kentucky", "Norse"),
    ("Northwestern", "Wildcats"),
    ("Northwestern State", "Demons"),
    ("Notre Dame", "Fighting Irish"),
    ("Oakland", "Golden Grizzlies"),
    ("Ohio", "Bobcats"),
    ("Ohio State", "Buckeyes"),
    ("Oklahoma", "Sooners"),
    ("Oklahoma State", "Cowboys"),
    ("Old Dominion", "Monarchs"),
    ("Ole Miss", "Mississippi", "Rebels"),
    ("Omaha", "Mavericks"),
    ("Oral Roberts", "Golden Eagles"),
    ("Oregon", "Ducks"),
    ("Oregon State", "Beavers"),
    ("Pacific", "Tigers"),
    ("Penn", "Pennsylvania", "Quakers"),
    ("Penn State", "Nittany Lions"),
    ("Pepperdine", "Waves"),
    ("Pittsburgh", "Pitt", "Panthers"),
    ("Portland", "Pilots"),
    ("Portland State", "Vikings"),
    ("Prairie View A&M", "Panthers"),
    ("Presbyterian", "Blue Hose"),
    ("Princeton", "Tigers"),
    ("Providence", "Friars"),
    ("Purdue", "Boilermakers"),
    ("Purdue Fort Wayne", "Mastodons"),
    ("Quinnipiac", "Bobcats"),
    ("Radford", "Highlanders"),
    ("Rhode Island", "Rams"),
    ("Rice", "Owls"),
    ("Richmond", "Spiders"),
    ("Rider", "Broncs"),
    ("Robert Morris", "Colonials"),
    ("Rutgers", "Scarlet Knights"),
    ("Sacramento State", "Hornets"),
    ("Sacred Heart", "Pioneers"),
    ("Saint Francis (PA)", "Saint Francis PA", "Red Flash"),
    ("Saint Joseph's", "Saint Josephs", "Hawks"),
    ("Saint Louis", "Billikens"),
    ("Saint Mary's", "Saint Marys", "Gaels"),
    ("Saint Peter's", "Saint Peters", "Peacocks"),
    ("Sam Houston", "Bearkats"),
    ("Samford", "Bulldogs"),
    ("San Diego", "Toreros"),
    ("San Diego State", "Aztecs"),
    ("San Francisco", "Dons"),
    ("San Jose State", "Spartans"),
    ("Santa Clara", "Broncos"),
    ("Seattle", "Redhawks"),
    ("Seton Hall", "Pirates"),
    ("Siena", "Saints"),
    ("SIU Edwardsville", "SIUE", "Cougars"),
    ("SMU", "Mustangs"),
    ("South Alabama", "Jaguars"),
    ("South Carolina", "Gamecocks"),
    ("South Carolina State", "Bulldogs"),
    ("South Carolina Upstate", "Spartans"),
    ("South Dakota", "Coyotes"),
    ("South Dakota State", "Jackrabbits"),
    ("South Florida", "USF", "Bulls"),
    ("Southeast Missouri State", "Redhawks"),
    ("Southeastern Louisiana", "Lions"),
    ("Southern", "Jaguars"),
    ("Southern Illinois", "Salukis"),
    ("Southern Miss", "Golden Eagles"),
    ("Southern Utah", "Thunderbirds"),
    ("St. Bonaventure", "Bonnies"),
    ("St. John's", "St. Johns", "Red Storm"),
    ("St. Thomas", "Tommies"),
    ("Stanford", "Cardinal"),
    ("Stephen F. Austin", "Lumberjacks"),
    ("Stetson", "Hatters"),
    ("Stonehill", "Skyhawks"),
    ("Syracuse", "Orange"),
    ("Tarleton State", "Texans"),
    ("TCU", "Horned Frogs"),
    ("Temple", "Owls"),
    ("Tennessee", "Volunteers", "Vols"),
    ("Tennessee State", "Tigers"),
    ("Tennessee Tech", "Golden Eagles"),
    ("Texas", "Longhorns"),
    ("Texas A&M", "Aggies"),
    ("Texas A&M-Corpus Christi", "Islanders"),
    ("Texas Southern", "Tigers"),
    ("Texas State", "Bobcats"),
    ("Texas Tech", "Red Raiders"),
    ("The Citadel", "Bulldogs"),
    ("Toledo", "Rockets"),
    ("Towson", "Tigers"),
    ("Troy", "Trojans"),
    ("Tulane", "Green Wave"),
    ("Tulsa", "Golden Hurricane"),
    ("UAB", "Blazers"),
    ("UC Davis", "Aggies"),
    ("UC Irvine", "Anteaters"),
    ("UC Riverside", "Highlanders"),
    ("UC San Diego", "Tritons"),
    ("UC Santa Barbara", "Gauchos"),
    ("UCF", "Knights"),
    ("UCLA", "Bruins"),
    ("UMass Lowell", "River Hawks"),
    ("UNC Asheville", "Bulldogs"),
    ("UNC Greensboro", "Spartans"),
    ("UNC Wilmington", "Seahawks"),
    ("UNLV", "Rebels"),
    ("USC", "Trojans"),
    ("USC Upstate", "Spartans"),
    ("UT Arlington", "Mavericks"),
    ("UT Martin", "Skyhawks"),
    ("UT Rio Grande Valley", "Vaqueros"),
    ("Utah", "Utes"),
    ("Utah State", "Aggies"),
    ("Utah Tech", "Trailblazers"),
    ("Utah Valley", "Wolverines"),
    ("UTEP", "Miners"),
    ("UTSA", "Roadrunners"),
    ("Valparaiso", "Beacons"),
    ("Vanderbilt", "Commodores"),
    ("VCU", "Rams"),
    ("Vermont", "Catamounts"),
    ("Villanova", "Wildcats"),
    ("Virginia", "Cavaliers"),
    ("Virginia Tech", "Hokies"),
    ("VMI", "Keydets"),
    ("Wagner", "Seahawks"),
    ("Wake Forest", "Demon Deacons"),
    ("Washington", "Huskies"),
    ("Washington State", "Cougars"),
    ("Weber State", "Wildcats"),
    ("West Virginia", "Mountaineers"),
    ("Western Carolina", "Catamounts"),
    ("Western Illinois", "Leathernecks"),
    ("Western Kentucky", "Hilltoppers"),
    ("Western Michigan", "Broncos"),
    ("Wichita State", "Shockers"),
    ("William & Mary", "William and Mary", "Tribe"),
    ("Winthrop", "Eagles"),
    ("Wisconsin", "Badgers"),
    ("Wofford", "Terriers"),
    ("Wright State", "Raiders"),
    ("Wyoming", "Cowboys"),
    ("Xavier", "Musketeers"),
    ("Yale", "Bulldogs"),
    ("Youngstown State", "Penguins"),
]


def _college_teams(rows: list[tuple[str, ...]]) -> list[dict]:
    """College maps use full school name as code; extras must be globally unique."""

    seen: set[str] = set()
    teams: list[dict] = []
    for row in rows:
        code = row[0]
        aliases = [code]
        if code in seen:
            raise ValueError(f"duplicate college code {code!r}")
        seen.add(code)
        for extra in row[1:]:
            label = str(extra).strip()
            if not label or label in seen:
                continue
            seen.add(label)
            aliases.append(label)
        teams.append({"code": code, "aliases": aliases})
    return teams


def _apply_college_disambig(
    teams: list[dict], disambig: list[tuple[str, ...]]
) -> list[dict]:
    by_code = {t["code"]: t for t in teams}
    seen = {alias for t in teams for alias in t["aliases"]}
    for row in disambig:
        code = row[0]
        target = by_code.get(code)
        if target is None:
            continue
        for extra in row[1:]:
            label = str(extra).strip()
            if not label or label in seen:
                continue
            seen.add(label)
            target["aliases"].append(label)
    return list(by_code.values())


def _write_college(
    name: str,
    package_key: str,
    rows: list[tuple[str, ...]],
    *,
    disambig: list[tuple[str, ...]] | None = None,
    package_aliases: list[str] | None = None,
) -> None:
    teams = _college_teams(rows)
    if disambig:
        teams = _apply_college_disambig(teams, disambig)
    _write(name, package_key, teams, package_aliases=package_aliases)


def _school_names_only(rows: list[tuple[str, ...]]) -> list[tuple[str, ...]]:
    return [(row[0],) for row in rows]


if __name__ == "__main__":
    main()
